INSERT INTO tutorials (title, category, description, published) VALUES
('Introduzione a HTML', 'Web Development', 'Guida base ai tag HTML, struttura di una pagina e semantica.', TRUE),
('CSS Avanzato', 'Web Development', 'Approfondimento su Flexbox, Grid e animazioni CSS.', TRUE),
('JavaScript per Principianti', 'Programming', 'Le basi del linguaggio JavaScript con esempi pratici.', TRUE),
('Manipolazione DOM', 'Programming', 'Come modificare dinamicamente gli elementi HTML con JS.', TRUE),
('Angular Fundamentals', 'Framework', 'Introduzione al framework Angular e alla creazione di componenti.', TRUE),
('Routing in Angular', 'Framework', 'Gestione delle rotte e navigazione tra componenti in Angular.', FALSE),
('MySQL Base', 'Database', 'Creazione di tabelle, query SELECT e JOIN in MySQL.', TRUE),
('MySQL Avanzato', 'Database', 'Stored procedure, trigger e ottimizzazione delle query.', FALSE),
('Introduzione a Java', 'Programming', 'Le basi della sintassi Java, variabili e tipi di dato.', TRUE),
('Programmazione a Oggetti in Java', 'Programming', 'Classi, oggetti, ereditarietà e polimorfismo.', TRUE),
('Spring Boot Base', 'Backend', 'Creazione di API REST con Spring Boot e Maven.', TRUE),
('Spring Security', 'Backend', 'Autenticazione e autorizzazione con Spring Security.', FALSE),
('Responsive Design', 'Web Design', 'Tecniche per rendere i siti web adattabili a ogni dispositivo.', TRUE),
('Git e GitHub', 'DevOps', 'Gestione del versionamento e collaborazione tramite Git.', TRUE),
('Docker Essentials', 'DevOps', 'Concetti base dei container e creazione di immagini Docker.', TRUE),
('API RESTful Design', 'Backend', 'Come progettare e documentare API REST in modo efficiente.', TRUE),
('Testing con JUnit', 'Testing', 'Scrivere test automatici per applicazioni Java.', FALSE),
('Node.js e Express', 'Backend', 'Creazione di server web leggeri e performanti con Node.js.', TRUE),
('Sicurezza Web', 'Cybersecurity', 'Protezione da attacchi comuni come XSS e SQL Injection.', TRUE),
('Deploy su AWS', 'Cloud', 'Guida passo passo al deploy di un’app web su Amazon Web Services.', FALSE);
